Updated the CONTRIBUTORS.md
Your-First-Open-Source-Project/start-here pull request #470
Opened 2024-05-07 17:54 UTC by Eztosin

2024-05-07 17:58 UTC, Eztosin commented
@melvincwng I actually made the commit months back, unfortunately I didn't request pr. I've corrected the file now. I apologize for any inconveniences caused.

2024-05-08 15:40 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-05-08 15:40 UTC, StackOverflowIsBetterThanAnyAI commented on CONTRIBUTORS.md
> +203.
the additional line is not needed

2024-05-08 15:56 UTC, merged

2024-05-08 15:56 UTC, melvincwng commented
Hey there,

Thanks for your PR & contribution :wave:!

Don't forget to join **follow me**, **join our organization**, & **follow our organization** to stay updated with the latest developments 💻

Thank you, and have a good day ahead 😊